//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeviceManage_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeviceManage_Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DeviceManage_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 报警事件 的本地化字符串。
        /// </summary>
        internal static string AlarmMast {
            get {
                return ResourceManager.GetString("AlarmMast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警时长 的本地化字符串。
        /// </summary>
        internal static string AlarmTime {
            get {
                return ResourceManager.GetString("AlarmTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器编号 的本地化字符串。
        /// </summary>
        internal static string ControlCode {
            get {
                return ResourceManager.GetString("ControlCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器管理 的本地化字符串。
        /// </summary>
        internal static string ControlManage {
            get {
                return ResourceManager.GetString("ControlManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器名称 的本地化字符串。
        /// </summary>
        internal static string ControlName {
            get {
                return ResourceManager.GetString("ControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口号 的本地化字符串。
        /// </summary>
        internal static string ControlPort {
            get {
                return ResourceManager.GetString("ControlPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器序列号 的本地化字符串。
        /// </summary>
        internal static string ControlSerial {
            get {
                return ResourceManager.GetString("ControlSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器状态 的本地化字符串。
        /// </summary>
        internal static string ControlStatus {
            get {
                return ResourceManager.GetString("ControlStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器类型 的本地化字符串。
        /// </summary>
        internal static string ControlType {
            get {
                return ResourceManager.GetString("ControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期范围 的本地化字符串。
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在删除控制器及配置信息... 的本地化字符串。
        /// </summary>
        internal static string DeletingControlInfo {
            get {
                return ResourceManager.GetString("DeletingControlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        internal static string DeviceManage {
            get {
                return ResourceManager.GetString("DeviceManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门报警 的本地化字符串。
        /// </summary>
        internal static string DoorAlerm {
            get {
                return ResourceManager.GetString("DoorAlerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开门超时报警 的本地化字符串。
        /// </summary>
        internal static string DoorAlerm2Long {
            get {
                return ResourceManager.GetString("DoorAlerm2Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门编号 的本地化字符串。
        /// </summary>
        internal static string DoorCode {
            get {
                return ResourceManager.GetString("DoorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门管理 的本地化字符串。
        /// </summary>
        internal static string DoorManage {
            get {
                return ResourceManager.GetString("DoorManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门名称 的本地化字符串。
        /// </summary>
        internal static string DoorName {
            get {
                return ResourceManager.GetString("DoorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间段名称 的本地化字符串。
        /// </summary>
        internal static string DoorTimeName {
            get {
                return ResourceManager.GetString("DoorTimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间段管理 的本地化字符串。
        /// </summary>
        internal static string DoortTimeMange {
            get {
                return ResourceManager.GetString("DoortTimeMange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下发卡信息 的本地化字符串。
        /// </summary>
        internal static string DownloadInfo {
            get {
                return ResourceManager.GetString("DownloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定下发选中记录？ 的本地化字符串。
        /// </summary>
        internal static string DownloadInfoConfirm {
            get {
                return ResourceManager.GetString("DownloadInfoConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胁持密码 的本地化字符串。
        /// </summary>
        internal static string DuressPIN {
            get {
                return ResourceManager.GetString("DuressPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火警报警时间 的本地化字符串。
        /// </summary>
        internal static string FireTime {
            get {
                return ResourceManager.GetString("FireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组的组号 的本地化字符串。
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别方式 的本地化字符串。
        /// </summary>
        internal static string Identify {
            get {
                return ResourceManager.GetString("Identify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效卡 的本地化字符串。
        /// </summary>
        internal static string IllegalCard {
            get {
                return ResourceManager.GetString("IllegalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效时间 的本地化字符串。
        /// </summary>
        internal static string IllegalTime {
            get {
                return ResourceManager.GetString("IllegalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别方式 的本地化字符串。
        /// </summary>
        internal static string Indetify {
            get {
                return ResourceManager.GetString("Indetify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        internal static string IPAddr {
            get {
                return ResourceManager.GetString("IPAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期截止 的本地化字符串。
        /// </summary>
        internal static string LimitDate {
            get {
                return ResourceManager.GetString("LimitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 互锁设置 的本地化字符串。
        /// </summary>
        internal static string LockEach {
            get {
                return ResourceManager.GetString("LockEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1-2门互锁 的本地化字符串。
        /// </summary>
        internal static string LockEach12 {
            get {
                return ResourceManager.GetString("LockEach12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3-4门互锁 的本地化字符串。
        /// </summary>
        internal static string LockEach34 {
            get {
                return ResourceManager.GetString("LockEach34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多人开门数量 的本地化字符串。
        /// </summary>
        internal static string MCardsOpen {
            get {
                return ResourceManager.GetString("MCardsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多人开门方向 的本地化字符串。
        /// </summary>
        internal static string MCardsOpenInOut {
            get {
                return ResourceManager.GetString("MCardsOpenInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开门超时(S) 的本地化字符串。
        /// </summary>
        internal static string OpenOutTime {
            get {
                return ResourceManager.GetString("OpenOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开门时间(S) 的本地化字符串。
        /// </summary>
        internal static string OpenTime {
            get {
                return ResourceManager.GetString("OpenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双向检测 的本地化字符串。
        /// </summary>
        internal static string PassBack {
            get {
                return ResourceManager.GetString("PassBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确格式的IP地址！ 的本地化字符串。
        /// </summary>
        internal static string PleaseInputIPAddr {
            get {
                return ResourceManager.GetString("PleaseInputIPAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保留 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始时间 的本地化字符串。
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将更新与该控制器有关的权限信息，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string UpdateControlInfo {
            get {
                return ResourceManager.GetString("UpdateControlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新信息 的本地化字符串。
        /// </summary>
        internal static string UpdateInfo {
            get {
                return ResourceManager.GetString("UpdateInfo", resourceCulture);
            }
        }
    }
}
