//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmployeeManage_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeManage_Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EmployeeManage_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 考勤 的本地化字符串。
        /// </summary>
        internal static string BeKQ {
            get {
                return ResourceManager.GetString("BeKQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生日 的本地化字符串。
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌号 的本地化字符串。
        /// </summary>
        internal static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡号 的本地化字符串。
        /// </summary>
        internal static string CardNo {
            get {
                return ResourceManager.GetString("CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门 的本地化字符串。
        /// </summary>
        internal static string Dept {
            get {
                return ResourceManager.GetString("Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下发卡信息 的本地化字符串。
        /// </summary>
        internal static string DownLoadCard {
            get {
                return ResourceManager.GetString("DownLoadCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工号 的本地化字符串。
        /// </summary>
        internal static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工查询 的本地化字符串。
        /// </summary>
        internal static string EmployeeSearch {
            get {
                return ResourceManager.GetString("EmployeeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期 的本地化字符串。
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文名 的本地化字符串。
        /// </summary>
        internal static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住址 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位 的本地化字符串。
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后一次刷卡 的本地化字符串。
        /// </summary>
        internal static string LastEvent {
            get {
                return ResourceManager.GetString("LastEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离职 的本地化字符串。
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离职时间 的本地化字符串。
        /// </summary>
        internal static string LeaveDate {
            get {
                return ResourceManager.GetString("LeaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注1 的本地化字符串。
        /// </summary>
        internal static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注2 的本地化字符串。
        /// </summary>
        internal static string Note2 {
            get {
                return ResourceManager.GetString("Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注3 的本地化字符串。
        /// </summary>
        internal static string Note3 {
            get {
                return ResourceManager.GetString("Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注4 的本地化字符串。
        /// </summary>
        internal static string Note4 {
            get {
                return ResourceManager.GetString("Note4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证 的本地化字符串。
        /// </summary>
        internal static string PersonCode {
            get {
                return ResourceManager.GetString("PersonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人1寸照片 的本地化字符串。
        /// </summary>
        internal static string PersonPhoto {
            get {
                return ResourceManager.GetString("PersonPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片1 的本地化字符串。
        /// </summary>
        internal static string Photo1 {
            get {
                return ResourceManager.GetString("Photo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片2 的本地化字符串。
        /// </summary>
        internal static string Photo2 {
            get {
                return ResourceManager.GetString("Photo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        internal static string Privilege {
            get {
                return ResourceManager.GetString("Privilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限配置 的本地化字符串。
        /// </summary>
        internal static string PrivilegeSet {
            get {
                return ResourceManager.GetString("PrivilegeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登记日期 的本地化字符串。
        /// </summary>
        internal static string RegDate {
            get {
                return ResourceManager.GetString("RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册时间 的本地化字符串。
        /// </summary>
        internal static string RegTime {
            get {
                return ResourceManager.GetString("RegTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发卡 的本地化字符串。
        /// </summary>
        internal static string SendCard {
            get {
                return ResourceManager.GetString("SendCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传 的本地化字符串。
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作信息 的本地化字符串。
        /// </summary>
        internal static string WorkInfo {
            get {
                return ResourceManager.GetString("WorkInfo", resourceCulture);
            }
        }
    }
}
