//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMsg_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMsg_Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMsg_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 门禁权限不存在 的本地化字符串。
        /// </summary>
        internal static string ACCESS_NOT_EXIST {
            get {
                return ResourceManager.GetString("ACCESS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能删除自己 的本地化字符串。
        /// </summary>
        internal static string CANT_DELETE_YOURSELF {
            get {
                return ResourceManager.GetString("CANT_DELETE_YOURSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备连接失败 的本地化字符串。
        /// </summary>
        internal static string CONNECT_FAILED {
            get {
                return ResourceManager.GetString("CONNECT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器IP地址重复 的本地化字符串。
        /// </summary>
        internal static string CONTROL_IP_EXIST {
            get {
                return ResourceManager.GetString("CONTROL_IP_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器不存在 的本地化字符串。
        /// </summary>
        internal static string CONTROL_NOT_EXIST {
            get {
                return ResourceManager.GetString("CONTROL_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器类型不能为空 的本地化字符串。
        /// </summary>
        internal static string CONTROL_TYPE_IS_EMPTY {
            get {
                return ResourceManager.GetString("CONTROL_TYPE_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库操作失败 的本地化字符串。
        /// </summary>
        internal static string DATABASE_FAIL {
            get {
                return ResourceManager.GetString("DATABASE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据转换错误 的本地化字符串。
        /// </summary>
        internal static string DATA_CONVERT_ERROR {
            get {
                return ResourceManager.GetString("DATA_CONVERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除控制器失败 的本地化字符串。
        /// </summary>
        internal static string DELETE_CONTROL_ERR {
            get {
                return ResourceManager.GetString("DELETE_CONTROL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已存在 的本地化字符串。
        /// </summary>
        internal static string DEPTNAME_EXIST {
            get {
                return ResourceManager.GetString("DEPTNAME_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门存在子部门 的本地化字符串。
        /// </summary>
        internal static string DEPT_HAS_CHILDREN {
            get {
                return ResourceManager.GetString("DEPT_HAS_CHILDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类型获取失败 的本地化字符串。
        /// </summary>
        internal static string DEVICE_TYPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEVICE_TYPE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门不存在 的本地化字符串。
        /// </summary>
        internal static string DOOR_NOT_EXIST {
            get {
                return ResourceManager.GetString("DOOR_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工卡号重复 的本地化字符串。
        /// </summary>
        internal static string EMPLOYEE_CARDNO_DUPLICATE {
            get {
                return ResourceManager.GetString("EMPLOYEE_CARDNO_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工卡编号不存在 的本地化字符串。
        /// </summary>
        internal static string EMPLOYEE_CARD_NOT_EXIST {
            get {
                return ResourceManager.GetString("EMPLOYEE_CARD_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工号已存在 的本地化字符串。
        /// </summary>
        internal static string EMPLOYEE_CODE_EXIST {
            get {
                return ResourceManager.GetString("EMPLOYEE_CODE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工序号不存在 的本地化字符串。
        /// </summary>
        internal static string EMPLOYEE_INDEX_NOT_EXIST {
            get {
                return ResourceManager.GetString("EMPLOYEE_INDEX_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工不存在 的本地化字符串。
        /// </summary>
        internal static string EMPLOYEE_NOT_EXIST {
            get {
                return ResourceManager.GetString("EMPLOYEE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 假日不存在 的本地化字符串。
        /// </summary>
        internal static string HOLIDAY_NOT_EXIST {
            get {
                return ResourceManager.GetString("HOLIDAY_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        internal static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象不存在 的本地化字符串。
        /// </summary>
        internal static string OBJECT_NOT_EXIST {
            get {
                return ResourceManager.GetString("OBJECT_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原密码错误 的本地化字符串。
        /// </summary>
        internal static string OLD_PASSWORD_WRONG {
            get {
                return ResourceManager.GetString("OLD_PASSWORD_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备操作失败 的本地化字符串。
        /// </summary>
        internal static string OPERATE_DEVICE_FAILED {
            get {
                return ResourceManager.GetString("OPERATE_DEVICE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备不在线 的本地化字符串。
        /// </summary>
        internal static string OPERATE_DEVICE_NOT_ONLINE {
            get {
                return ResourceManager.GetString("OPERATE_DEVICE_NOT_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string OPERATE_FAILED {
            get {
                return ResourceManager.GetString("OPERATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string OPERATE_SUCCESS {
            get {
                return ResourceManager.GetString("OPERATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已存在 的本地化字符串。
        /// </summary>
        internal static string USERNAME_EXIST {
            get {
                return ResourceManager.GetString("USERNAME_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户或密码错误 的本地化字符串。
        /// </summary>
        internal static string USERNAME_PASSWORD_WRONG {
            get {
                return ResourceManager.GetString("USERNAME_PASSWORD_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已存在 的本地化字符串。
        /// </summary>
        internal static string USER_EXISTED {
            get {
                return ResourceManager.GetString("USER_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string USER_NOT_EXISTED {
            get {
                return ResourceManager.GetString("USER_NOT_EXISTED", resourceCulture);
            }
        }
    }
}
