//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Monitor_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Monitor_Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Monitor_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 报警 的本地化字符串。
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警解除 的本地化字符串。
        /// </summary>
        internal static string AlarmRemove {
            get {
                return ResourceManager.GetString("AlarmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡号 的本地化字符串。
        /// </summary>
        internal static string CardNo {
            get {
                return ResourceManager.GetString("CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关门 的本地化字符串。
        /// </summary>
        internal static string CloseDoor {
            get {
                return ResourceManager.GetString("CloseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器 的本地化字符串。
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下发设备卡信息 的本地化字符串。
        /// </summary>
        internal static string DeviceDownload {
            get {
                return ResourceManager.GetString("DeviceDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备监控 的本地化字符串。
        /// </summary>
        internal static string DeviceMonitor {
            get {
                return ResourceManager.GetString("DeviceMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门 的本地化字符串。
        /// </summary>
        internal static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件时间 的本地化字符串。
        /// </summary>
        internal static string EventTime {
            get {
                return ResourceManager.GetString("EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件类型 的本地化字符串。
        /// </summary>
        internal static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火警 的本地化字符串。
        /// </summary>
        internal static string FireAlarm {
            get {
                return ResourceManager.GetString("FireAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火警解除 的本地化字符串。
        /// </summary>
        internal static string FireAlarmRemove {
            get {
                return ResourceManager.GetString("FireAlarmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新事件 的本地化字符串。
        /// </summary>
        internal static string LatestEvent {
            get {
                return ResourceManager.GetString("LatestEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁门 的本地化字符串。
        /// </summary>
        internal static string LockDoor {
            get {
                return ResourceManager.GetString("LockDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开门 的本地化字符串。
        /// </summary>
        internal static string OpenDoor {
            get {
                return ResourceManager.GetString("OpenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁 的本地化字符串。
        /// </summary>
        internal static string UnlockDoor {
            get {
                return ResourceManager.GetString("UnlockDoor", resourceCulture);
            }
        }
    }
}
